site_name: My Docs
site_description: Appunti Comunicazioni Numeriche
site_url: https://github.com/MainKronos/Comunicazioni-Numeriche

theme:
  name: 'material'
  language: it
  palette:
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      toggle:
        icon: 'material/lightbulb'
        name: "Switch to dark mode"
    - scheme: 'slate'
      media: '(prefers-color-scheme: dark)'
      primary: 'blue'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'
  icon:
    repo: fontawesome/brands/github

repo_name: MainKronos/Comunicazioni-Numeriche
repo_url: https://github.com/MainKronos/Comunicazioni-Numeriche

nav:
  - Home: 'index.md'
  - Teoria Dei Segnali: 'teoria_segnali.md'
  - Teoria Dei Codici: 'teoria_codici.md'

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/katex.js 
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css